FROM debian

RUN apt update
RUN apt install apt-utils -y
RUN apt install gcc -y
RUN apt install libpam0g-dev -y
RUN apt install cmake -y
RUN apt install make -y
RUN apt install build-essential -y
RUN apt install sudo -y
RUN apt install valgrind -y